apache/bahir-flink

flink-connector-redis/pom.xml, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisClusterConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisConfigBase.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisPoolConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisSentinelConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilder.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisConfigBaseTest.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/config/JedisClusterConfigTest.java
Upgrade jedis to 2.9.0 and add password for redis cluster sink.
=> [BAHIR-205] Support configure password for redis cluster

flink-connector-kudu/pom.xml
=> [BAHIR-209] upgrade kudu version to 1.10.0

.travis.yml, pom.xml
=> [BAHIR-210] upgrade flink to 1.8.1

flink-connector-kudu/src/main/java/org/apache/flink/connectors/kudu/connector/KuduRow.java, flink-connector-kudu/src/main/java/org/apache/flink/connectors/kudu/connector/writer/KuduWriter.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/batch/KuduOuputFormatTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/connector/KuduDatabase.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/streaming/KuduSinkTest.java
Sometimes we don't want to upsert all columns of a kudu table. So we need support the function that upsert part of columns of a kudu table.
=> add support "upsert part of columns of a kudu table"

flink-connector-redis/README.md, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisSink.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisTableSink.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisTableSinkFactory.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisClusterContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/hanlder/RedisMapperHandler.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommand.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/RedisDataType.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/row/HIncrByMapper.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/row/RowRedisMapper.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/descriptor/Redis.java
add hincrby and repair Redis Cluster example code
=> connector-redis

.travis.yml
Update travis to last working version
=> [BAHIR-244] Update travis dist to bionic

.asf.yaml, pom.xml
more info in [here](https://issues.apache.org/jira/browse/BAHIR-245)
@lresende could you check
=> [BAHIR-245] Add git .asf.yaml file

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisTableSinkFactory.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/handler/FlinkJedisClusterConfigHandler.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/descriptor/RedisValidator.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/RedisHandlerTest.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/config/JedisClusterConfigTest.java
Now redis cluster sink setting password is not supported
=> support set redis cluster password

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisClusterContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisContainer.java
=> [BAHIR-265] Fix Java format print mismatch

flink-connector-redis/pom.xml
=> [BAHIR-264] Dedup dependencies in flink-connector-redis

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/handler/FlinkJedisClusterConfigHandler.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/handler/FlinkJedisSentinelConfigHandler.java
Use java8 stream better according to IntelliJ hints
=> Cleanup flink-connector-redis so that it uses java8 stream better

.travis.yml, flink-connector-netty/pom.xml, flink-connector-netty/src/test/scala/org/apache/flink/streaming/connectors/netty/example/StreamSqlExample.scala, pom.xml
2. fix netty connector unit test
=> 1. update flink version to 1.11.3

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilder.java
=> DRYer RedisCommandsContainerBuilder

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisClusterConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisPoolConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisSentinelConfig.java
=> Fix FlinkJedisConfigBase names in toString methods

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisClusterConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisConfigBase.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisPoolConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisSentinelConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilder.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisConfigBaseTest.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilderTest.java
The PR address @eskabetxe 's comment https://github.com/apache/bahir-flink/pull/104/files#r556403547
@eskabetxe Let me know if you have any other concern. If not, I will add comments to the code.
=> [BAHIR-247] Provide connection validation/idle testing for Flink-Redis Connector

flink-connector-flume/pom.xml, flink-connector-kudu/pom.xml, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/batch/KuduInputFormatTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/batch/KuduOutputFormatTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/connector/KuduTestBase.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/streaming/KuduSinkTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/table/KuduCatalogTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/table/KuduTableFactoryTest.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/table/KuduTableSourceITCase.java, flink-connector-kudu/src/test/java/org/apache/flink/connectors/kudu/table/KuduTableSourceTest.java
KuduTestHarness not work on all distributions of linux as it must be released by kudu team an artifact for that distribution.
This change the use of KuduTestHarness with TestContainers that allow to have a docker container for testing
=> [BAHIR-243] Change KuduTestHarness with TestContainers

flink-connector-influxdb2/src/main/java/org/apache/flink/streaming/connectors/influxdb/sink/InfluxDBSinkBuilder.java, flink-connector-influxdb2/src/main/java/org/apache/flink/streaming/connectors/influxdb/sink/InfluxDBSinkOptions.java, flink-connector-influxdb2/src/test/java/org/apache/flink/streaming/connectors/influxdb/sink/InfluxDBSinkBuilderTest.java, flink-connector-influxdb2/src/test/java/org/apache/flink/streaming/connectors/influxdb/util/InfluxDBContainer.java
See JIRA ticket: https://issues.apache.org/jira/browse/BAHIR-284
=> [BAHIR-284] add option to use token authentication for influxdb2

README.md, flink-connector-activemq/README.md, flink-connector-akka/README.md, flink-connector-flume/README.md, flink-connector-influxdb/README.md, flink-connector-influxdb2/README.md, flink-connector-kudu/README.md, flink-connector-netty/README.md, flink-connector-pinot/README.md, flink-connector-redis/README.md, pom.xml
Add license to README.md files
=> [BAHIR-312] Add license header to README.md files

flink-connector-redis/pom.xml, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/config/FlinkJedisClusterConfig.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisClusterContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilder.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/RedisSinkITCase.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/RedisSinkTest.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/config/JedisClusterConfigTest.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainerBuilderTest.java
* updated jedis to 4.3.0
* added support for SSL cluster connections
=> [BAHIR-315] Redis connector: add Support for SSL connections for cluster

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisSink.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisClusterContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommand.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/RedisSinkITCase.java
=> [BAHIR-201] Redis: add hdel command

flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/RedisSink.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisClusterContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisCommandsContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/container/RedisContainer.java, flink-connector-redis/src/main/java/org/apache/flink/streaming/connectors/redis/common/mapper/RedisCommand.java, flink-connector-redis/src/test/java/org/apache/flink/streaming/connectors/redis/RedisSinkITCase.java
=> [BAHIR-285] Redis: add srem command
